name: CI

on:
  push:
    branches:
      - main

jobs:
  # -------------------------------------------------------------
  # Using GitHub's API is not supported for push events
  # -------------------------------------------------------------
  # 
  # ----------------------------------------------------------------------------------------------
  # Using local .git history
  # ----------------------------------------------------------------------------------------------
  # Event `push`: Compare the preceding remote commit -> to the current commit of the main branch 
  # ----------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: (CI) Dependencies update check
        run: |
          old_hash=git log -2 --format="%H" | awk -F: 'NR==2 {print $1}'
          echo $old_hash
          new_hash=git log -1 --format="%H"
          echo $new_hash
          changed_files=git diff --name-only 2f42e6e ba06e6a
          echo $changed_files
