name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: (CI) Dependencies update check
        run: |
          old_hash= git log -2 --format="%H" | awk -F: 'NR==2 {print $1}'
          echo $old_hash
          new_hash= git log -1 --format="%H"
          echo $new_hash
          changed_files= git diff --name-only $old_hash $new_hash
          echo $changed_files
